# Generated by Django 3.0 on 2021-05-17 11:32

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('course', '0008_auto_20210516_2053'),
    ]

    operations = [
        migrations.CreateModel(
            name='MultiChoiceQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(help_text='the question text', unique=True)),
                ('max_mark', models.IntegerField(help_text='score mark for the question')),
                ('course', models.ForeignKey(help_text='The course to hold this question', on_delete=django.db.models.deletion.CASCADE, to='course.CourseModel')),
            ],
        ),
        migrations.CreateModel(
            name='TheoryQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(help_text='the question text', unique=True)),
                ('max_mark', models.IntegerField(help_text='score mark for the question')),
                ('course', models.ForeignKey(help_text='The course to hold this question', on_delete=django.db.models.deletion.CASCADE, to='course.CourseModel')),
            ],
        ),
        migrations.CreateModel(
            name='OptionChoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option', models.TextField()),
                ('is_answer_option', models.BooleanField(default=False, help_text='mark if answer this option is the answer', verbose_name='Answer option')),
                ('question', models.ForeignKey(help_text='Multi-choice question option', on_delete=django.db.models.fields.CharField, to='assessment.MultiChoiceQuestion')),
            ],
            options={
                'verbose_name': 'Option Choice',
                'verbose_name_plural': 'Option Choices',
            },
        ),
    ]
