# Generated by Django 3.0 on 2021-05-17 12:26

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0008_auto_20210516_2053'),
        ('assessment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(help_text='the question text', unique=True)),
                ('max_mark', models.IntegerField(help_text='maximum score mark for the question')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('quiz', 'Quiz'), ('midsem', 'Mid Semester')], max_length=20, unique=True)),
                ('course', models.ForeignKey(help_text='The course to hold this question', on_delete=django.db.models.deletion.CASCADE, to='course.CourseModel')),
                ('questions', models.ManyToManyField(to='assessment.Question')),
            ],
        ),
        migrations.RemoveField(
            model_name='theoryquestion',
            name='course',
        ),
        migrations.AlterModelOptions(
            name='multichoicequestion',
            options={'verbose_name': 'Option Choice', 'verbose_name_plural': 'Option Choices'},
        ),
        migrations.RemoveField(
            model_name='multichoicequestion',
            name='course',
        ),
        migrations.RemoveField(
            model_name='multichoicequestion',
            name='max_mark',
        ),
        migrations.AddField(
            model_name='multichoicequestion',
            name='is_answer_option',
            field=models.BooleanField(default=False, help_text='mark if answer this option is the answer', verbose_name='Answer option'),
        ),
        migrations.AddField(
            model_name='multichoicequestion',
            name='option',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='OptionChoice',
        ),
        migrations.DeleteModel(
            name='TheoryQuestion',
        ),
        migrations.AlterField(
            model_name='multichoicequestion',
            name='question',
            field=models.ForeignKey(help_text='Multi-choice question option', on_delete=django.db.models.fields.CharField, to='assessment.Question'),
        ),
    ]
