# Generated by Django 3.0 on 2021-05-17 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0002_auto_20210517_1226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multichoicequestion',
            name='is_answer_option',
            field=models.BooleanField(default=False, help_text='Is this option is the answer?', verbose_name='Answer option'),
        ),
        migrations.AlterField(
            model_name='question',
            name='max_mark',
            field=models.IntegerField(help_text='maximum score mark for this question', null=True),
        ),
        migrations.AlterField(
            model_name='questiongroup',
            name='title',
            field=models.CharField(choices=[('quiz', 'Quiz'), ('quiz1', 'Quiz 1'), ('quiz2', 'Quiz 2'), ('quiz3', 'Quiz 3'), ('quiz4', 'Quiz 4'), ('midsem', 'Mid Semester')], max_length=20, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='multichoicequestion',
            unique_together={('is_answer_option', 'question')},
        ),
    ]
