# Generated by Django 3.0 on 2021-05-17 18:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0003_auto_20210517_1808'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questiongroup',
            name='questions',
        ),
        migrations.AddField(
            model_name='question',
            name='group',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='assessment.QuestionGroup'),
            preserve_default=False,
        ),
    ]
