# Generated by Django 3.0 on 2021-05-17 20:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0005_auto_20210517_1940'),
    ]

    operations = [
        migrations.AddField(
            model_name='questiongroup',
            name='updated',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
