# Generated by Django 3.0 on 2021-05-17 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0006_questiongroup_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='questiongroup',
            name='questions_type',
            field=models.CharField(choices=[('multichoice', 'Multi Choice'), ('theory', 'Theory')], default='multichoice', max_length=20),
        ),
    ]
