# Generated by Django 3.0 on 2021-05-17 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0010_auto_20210517_2122'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='created_by',
        ),
    ]
