# Generated by Django 3.0 on 2021-05-18 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0011_remove_question_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='questiongroup',
            name='total_marks',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='question',
            name='max_mark',
            field=models.IntegerField(blank=True, help_text='maximum score mark for this question', null=True),
        ),
    ]
