# Generated by Django 3.0 on 2021-05-18 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0012_auto_20210518_0044'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='multichoicequestion',
            unique_together=set(),
        ),
    ]
