# Generated by Django 3.0 on 2021-05-22 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0014_auto_20210522_1155'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ('pk', 'question_number', 'updated')},
        ),
        migrations.AlterField(
            model_name='question',
            name='max_mark',
            field=models.FloatField(blank=True, help_text='maximum score mark for this question', null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_number',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
