# Generated by Django 3.0 on 2021-05-22 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0015_auto_20210522_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_number',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
