# Generated by Django 3.0 on 2021-05-26 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0016_auto_20210522_1458'),
    ]

    operations = [
        migrations.AddField(
            model_name='questiongroup',
            name='status',
            field=models.CharField(choices=[('prepared', 'Prepared'), ('marked', 'Marked'), ('conducted', 'Conducted'), ('assessing', 'Assessing')], default='prepared', max_length=25),
        ),
    ]
