# Generated by Django 3.0 on 2021-05-26 21:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0018_auto_20210526_0928'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssessmentPreference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.TimeField(blank=True, null=True)),
                ('environment', models.CharField(blank=True, max_length=120, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('is_restricted', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='questiongroup',
            name='preference',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='assessment.AssessmentPreference'),
        ),
    ]
