# Generated by Django 3.0 on 2021-05-28 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_auto_20210517_1132'),
        ('assessment', '0020_auto_20210526_2302'),
    ]

    operations = [
        migrations.CreateModel(
            name='LectureScheme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField()),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assessment.Question')),
            ],
        ),
        migrations.AlterModelOptions(
            name='questiongroup',
            options={'ordering': ('pk', 'title', 'questions_type')},
        ),
        migrations.AddField(
            model_name='questiongroup',
            name='is_share_total_marks',
            field=models.BooleanField(default=False, help_text='Force total mark on question individual marks'),
        ),
        migrations.AlterField(
            model_name='assessmentpreference',
            name='due_date',
            field=models.DateTimeField(blank=True, help_text='The date and time assessment is schedule to', null=True, verbose_name='Due Date and Time'),
        ),
        migrations.AlterField(
            model_name='questiongroup',
            name='status',
            field=models.CharField(choices=[('prepared', 'Prepared'), ('marked', 'Marked'), ('conducted', 'Conducted'), ('conduct', 'Conduct'), ('assessing', 'Assessing')], default='prepared', max_length=25),
        ),
        migrations.CreateModel(
            name='TheoryMarkingScheme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answers', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='assessment.LectureScheme')),
                ('question_group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='assessment.QuestionGroup')),
            ],
        ),
        migrations.CreateModel(
            name='StudentTheoryAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField(blank=True, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.Student')),
            ],
        ),
        migrations.CreateModel(
            name='StudentMultiChoiceAnswers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assessment.MultiChoiceQuestion')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.Student')),
            ],
        ),
    ]
