# Generated by Django 3.0 on 2021-05-29 02:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0022_auto_20210528_1500'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentmultichoiceanswers',
            name='questions',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='assessment.QuestionGroup'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='questiongroup',
            name='is_share_total_marks',
            field=models.BooleanField(default=False, help_text='This will force share total mark on each question mark.'),
        ),
        migrations.AlterField(
            model_name='studentmultichoiceanswers',
            name='selected_option',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='assessment.MultiChoiceQuestion'),
        ),
    ]
