# Generated by Django 3.0 on 2021-05-30 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0024_auto_20210529_2112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentmultichoiceanswer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assessment.Question'),
        ),
    ]
