# Generated by Django 3.0 on 2021-05-30 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0025_auto_20210530_1250'),
    ]

    operations = [
        migrations.AddField(
            model_name='multichoicescripts',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
