# Generated by Django 3.0 on 2021-05-31 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0026_multichoicescripts_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='multichoicescripts',
            name='correct_answers',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='multichoicescripts',
            name='score',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
