# Generated by Django 3.0 on 2021-05-31 10:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0028_auto_20210531_1043'),
    ]

    operations = [
        migrations.AddField(
            model_name='multichoicescripts',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
