# Generated by Django 3.0 on 2021-05-31 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0029_multichoicescripts_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='multichoicescripts',
            name='time_remain',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
