# Generated by Django 3.0 on 2021-05-31 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0030_multichoicescripts_time_remain'),
    ]

    operations = [
        migrations.AddField(
            model_name='multichoicescripts',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
