# Generated by Django 3.0 on 2021-05-31 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0031_multichoicescripts_is_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='multichoicescripts',
            name='has_paused',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='multichoicescripts',
            name='is_canceled',
            field=models.BooleanField(default=False),
        ),
    ]
