# Generated by Django 3.0 on 2021-06-02 02:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0034_auto_20210602_0202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentmultichoiceanswer',
            name='selected_option',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='assessment.MultiChoiceQuestion'),
        ),
    ]
