# Generated by Django 3.0 on 2021-06-03 01:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_auto_20210528_1500'),
        ('lecture', '0003_auto_20210516_2037'),
        ('assessment', '0035_auto_20210602_0206'),
    ]

    operations = [
        migrations.CreateModel(
            name='Solution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assessment.Question')),
            ],
        ),
        migrations.CreateModel(
            name='StudentTheoryScript',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assessment.QuestionGroup')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.Student')),
            ],
        ),
        migrations.RemoveField(
            model_name='studenttheoryanswer',
            name='student',
        ),
        migrations.RemoveField(
            model_name='theorymarkingscheme',
            name='answers',
        ),
        migrations.AddField(
            model_name='studenttheoryanswer',
            name='question',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='assessment.Question'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='theorymarkingscheme',
            name='lecture',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='lecture.LectureModel'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='LectureScheme',
        ),
        migrations.AddField(
            model_name='solution',
            name='scheme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assessment.TheoryMarkingScheme'),
        ),
        migrations.AddField(
            model_name='studenttheoryanswer',
            name='script',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='assessment.StudentTheoryScript'),
            preserve_default=False,
        ),
    ]
