# Generated by Django 3.0 on 2021-06-03 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0036_auto_20210603_0124'),
    ]

    operations = [
        migrations.AddField(
            model_name='studenttheoryanswer',
            name='score',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
