# Generated by Django 3.0 on 2021-06-03 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0037_studenttheoryanswer_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='studenttheoryscript',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
