# Generated by Django 3.0 on 2021-06-03 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0038_studenttheoryscript_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='studenttheoryanswer',
            name='lecture_comment',
            field=models.TextField(help_text='Lectures comment on answer', null=True),
        ),
        migrations.AddField(
            model_name='studenttheoryscript',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
