# Generated by Django 3.0 on 2021-06-04 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0039_auto_20210603_2040'),
    ]

    operations = [
        migrations.AddField(
            model_name='studenttheoryscript',
            name='status',
            field=models.CharField(choices=[('mark', 'Marked'), ('marking', 'Marking'), ('pending', 'Pending'), ('submitted', 'Submitted'), ('assessing', 'Assessing')], default='assessing', max_length=60),
        ),
        migrations.AlterField(
            model_name='studenttheoryanswer',
            name='answer',
            field=models.TextField(blank=True, help_text='Your answer to the question.', null=True),
        ),
    ]
