# Generated by Django 3.0 on 2021-06-05 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0041_studenttheoryscript_submitted_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='multichoicescripts',
            name='status',
            field=models.CharField(choices=[('mark', 'Marked'), ('marking', 'Marking'), ('pending', 'Pending'), ('submitted', 'Submitted'), ('assessing', 'Assessing')], default='assessing', max_length=60),
        ),
    ]
