# Generated by Django 3.0 on 2021-06-07 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0043_auto_20210606_1318'),
    ]

    operations = [
        migrations.AddField(
            model_name='studenttheoryscript',
            name='score',
            field=models.FloatField(null=True),
        ),
    ]
