# Generated by Django 3.0 on 2021-06-07 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0045_auto_20210607_1112'),
    ]

    operations = [
        migrations.AddField(
            model_name='theorymarkingscheme',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='questiongroup',
            name='status',
            field=models.CharField(choices=[('prepared', 'Prepared'), ('marked', 'Marked'), ('conducted', 'Conducted'), ('conduct', 'Conduct'), ('published', 'Published')], default='prepared', max_length=25),
        ),
    ]
