# Generated by Django 3.0 on 2021-06-07 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0046_auto_20210607_1241'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ('id', 'question_number', 'updated')},
        ),
        migrations.AlterField(
            model_name='solution',
            name='answer',
            field=models.TextField(help_text='Solution to the question'),
        ),
        migrations.AlterField(
            model_name='solution',
            name='notes',
            field=models.TextField(blank=True, help_text='Notes on solution', null=True),
        ),
    ]
