# Generated by Django 3.0 on 2021-06-08 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0047_auto_20210607_2106'),
    ]

    operations = [
        migrations.AddField(
            model_name='questiongroup',
            name='academic_year',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='questiongroup',
            name='title',
            field=models.CharField(choices=[(None, '--------'), ('quiz', 'Quiz'), ('quiz1', 'Quiz 1'), ('quiz2', 'Quiz 2'), ('quiz3', 'Quiz 3'), ('quiz4', 'Quiz 4'), ('midsem', 'Mid Semester')], max_length=20),
        ),
    ]
