# Generated by Django 3.0 on 2021-06-10 18:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0049_auto_20210608_1748'),
    ]

    operations = [
        migrations.AddField(
            model_name='theorymarkingscheme',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='theorymarkingscheme',
            name='update_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='multichoicescripts',
            name='status',
            field=models.CharField(choices=[('marked', 'Marked'), ('marking', 'Marking'), ('pending', 'Pending'), ('submitted', 'Submitted'), ('assessing', 'Assessing'), ('published', 'Published')], default='assessing', max_length=60),
        ),
        migrations.AlterField(
            model_name='studenttheoryscript',
            name='status',
            field=models.CharField(choices=[('marked', 'Marked'), ('marking', 'Marking'), ('pending', 'Pending'), ('submitted', 'Submitted'), ('assessing', 'Assessing'), ('published', 'Published')], default='assessing', max_length=60),
        ),
    ]
