# Generated by Django 3.0 on 2021-06-10 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0050_auto_20210610_1823'),
    ]

    operations = [
        migrations.RenameField(
            model_name='theorymarkingscheme',
            old_name='update_at',
            new_name='updated_at',
        ),
    ]
