# Generated by Django 3.0 on 2021-06-11 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0051_auto_20210610_1824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studenttheoryanswer',
            name='lecture_comment',
            field=models.TextField(blank=True, help_text='Lectures comment on answer', null=True),
        ),
    ]
