# Generated by Django 3.0 on 2021-06-11 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0052_auto_20210611_0203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question',
            field=models.TextField(blank=True, help_text='the question text', null=True, unique=True),
        ),
    ]
