# Generated by Django 3.0 on 2021-06-11 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0053_auto_20210611_2008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question',
            field=models.TextField(help_text='the question text', null=True),
        ),
    ]
