# Generated by Django 3.2.5 on 2021-07-17 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0055_auto_20210717_0943'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assessmentpreference',
            options={'ordering': ('id',)},
        ),
        migrations.AlterField(
            model_name='questiongroup',
            name='preference',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='assessment.assessmentpreference'),
        ),
    ]
