# Generated by Django 3.2.5 on 2021-07-17 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0056_auto_20210717_0958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questiongroup',
            name='title',
            field=models.CharField(choices=[(None, '--------'), ('quiz', 'Quiz'), ('quiz1', 'Quiz 1'), ('quiz2', 'Quiz 2'), ('quiz3', 'Quiz 3'), ('quiz4', 'Quiz 4'), ('midsem', 'Mid Semester Quiz')], max_length=20),
        ),
    ]
