# Generated by Django 3.2.5 on 2021-08-04 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0057_alter_questiongroup_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessmentpreference',
            name='duration',
            field=models.DurationField(blank=True, help_text='The assessment duration in hours:minutes (eg; 2:30)', null=True),
        ),
        migrations.AlterField(
            model_name='questiongroup',
            name='title',
            field=models.CharField(choices=[(None, '--------'), ('quiz1', 'Quiz 1'), ('quiz2', 'Quiz 2'), ('quiz3', 'Quiz 3'), ('quiz4', 'Quiz 4'), ('quiz5', 'Quiz 5'), ('midsem', 'Mid Semester Quiz')], max_length=20),
        ),
    ]
