# Generated by Django 3.2.5 on 2021-09-03 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0011_alter_coursemodel_code'),
        ('assessment', '0058_auto_20210804_0626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessmentpreference',
            name='duration',
            field=models.DurationField(blank=True, help_text='The assessment duration in hours:minutes:seconds (eg; 0:30:00)', null=True),
        ),
        migrations.AlterUniqueTogether(
            name='questiongroup',
            unique_together={('title', 'course', 'questions_type')},
        ),
    ]
