# Generated by Django 3.2.5 on 2021-09-09 00:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0060_alter_questiongroup_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assessmentpreference',
            name='environment',
        ),
    ]
