# Generated by Django 3.2.5 on 2021-09-15 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0007_auto_20210717_0943'),
        ('assessment', '0061_remove_assessmentpreference_environment'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='studenttheoryscript',
            unique_together={('student', 'question_group')},
        ),
    ]
