# Generated by Django 3.0 on 2021-05-08 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CourseModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('short_name', models.CharField(max_length=100, unique=True)),
                ('level', models.CharField(choices=[('l1', 'Level 100'), ('l2', 'Level 200'), ('l3', 'Level 300'), ('l4', 'Level 400')], max_length=50)),
                ('semester', models.CharField(choices=[('s1', 'Semester 1'), ('s2', 'Semester 2')], max_length=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
