# Generated by Django 3.0 on 2021-05-08 22:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, unique=True, verbose_name='Level name')),
                ('number', models.IntegerField(unique=True, verbose_name='Level Number')),
            ],
        ),
        migrations.AlterField(
            model_name='coursemodel',
            name='semester',
            field=models.CharField(choices=[('s1', 'First Semester'), ('s2', 'Second Semester')], max_length=10),
        ),
        migrations.AlterField(
            model_name='coursemodel',
            name='level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.CourseLevel'),
        ),
    ]
