# Generated by Django 3.0 on 2021-05-08 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_auto_20210508_2206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courselevel',
            name='name',
            field=models.CharField(default='level', max_length=10, verbose_name='Level name'),
        ),
    ]
