# Generated by Django 3.0 on 2021-05-08 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_auto_20210508_2209'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='courselevel',
            options={'verbose_name': 'Level', 'verbose_name_plural': 'Levels'},
        ),
        migrations.AlterModelOptions(
            name='coursemodel',
            options={'verbose_name': 'Course', 'verbose_name_plural': 'Courses'},
        ),
        migrations.AlterUniqueTogether(
            name='courselevel',
            unique_together={('name', 'number')},
        ),
    ]
