# Generated by Django 3.0 on 2021-05-09 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_auto_20210508_2222'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='courselevel',
            options={'ordering': ('number',), 'verbose_name': 'Level', 'verbose_name_plural': 'Levels'},
        ),
    ]
