# Generated by Django 3.0 on 2021-05-15 09:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('programme', '0006_auto_20210515_0931'),
        ('course', '0005_auto_20210509_1753'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coursemodel',
            options={'ordering': ('level', 'name'), 'verbose_name': 'Course', 'verbose_name_plural': 'Courses'},
        ),
        migrations.AddField(
            model_name='coursemodel',
            name='programme',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='programme.Programme'),
        ),
    ]
