# Generated by Django 3.0 on 2021-05-16 20:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lecture', '0003_auto_20210516_2037'),
        ('course', '0007_auto_20210516_2037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursemodel',
            name='lecture',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lecture.LectureModel'),
        ),
    ]
