# Generated by Django 3.0 on 2021-05-18 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0008_auto_20210516_2053'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='coursemodel',
            unique_together=set(),
        ),
    ]
