# Generated by Django 3.2.5 on 2021-08-04 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0010_auto_20210717_0943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursemodel',
            name='code',
            field=models.CharField(max_length=100, unique=True, verbose_name='Course code'),
        ),
    ]
