# Generated by Django 3.2.5 on 2021-09-19 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0011_alter_coursemodel_code'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='courselevel',
            options={'ordering': ('name', 'number'), 'verbose_name': 'Level', 'verbose_name_plural': 'Levels'},
        ),
        migrations.AlterField(
            model_name='courselevel',
            name='name',
            field=models.CharField(default='Level', help_text='The letter part of the level', max_length=10, verbose_name='Level name'),
        ),
        migrations.AlterField(
            model_name='courselevel',
            name='number',
            field=models.IntegerField(help_text='The numeric part of the level', unique=True, verbose_name='Level Number'),
        ),
    ]
