# Generated by Django 3.0 on 2021-05-15 09:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('programme', '0006_auto_20210515_0931'),
        ('lecture', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecturemodel',
            name='programme',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='programme.Programme'),
        ),
    ]
