# Generated by Django 3.0 on 2021-05-16 20:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0002_remove_department_programme'),
        ('lecture', '0002_lecturemodel_programme'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lecturemodel',
            name='programme',
        ),
        migrations.AddField(
            model_name='lecturemodel',
            name='department',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='department.Department'),
            preserve_default=False,
        ),
    ]
