# Generated by Django 3.2.5 on 2021-07-23 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_groupmessage_from_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupmessage',
            name='group_name',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='groupmessage',
            name='title',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
