# Generated by Django 3.2.5 on 2021-07-23 14:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0004_auto_20210723_1413'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupmessage',
            name='to_group',
            field=models.CharField(choices=[('lecturers', 'Lecturers'), ('staffs', 'Lectures'), ('student', 'Students'), ('admins', 'Administrators'), ('all', 'All')], default='student', help_text='The category of people who will recieve this message', max_length=60, null=True, verbose_name='To'),
        ),
        migrations.AlterField(
            model_name='groupmessage',
            name='from_user',
            field=models.ForeignKey(help_text='the sender', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='From'),
        ),
        migrations.AlterField(
            model_name='groupmessage',
            name='group_name',
            field=models.CharField(help_text='Name of this group', max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='groupmessage',
            name='title',
            field=models.CharField(help_text='title of the message', max_length=120, null=True),
        ),
    ]
