# Generated by Django 3.2.5 on 2021-07-23 15:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0005_auto_20210723_1428'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupmessage',
            name='message',
        ),
        migrations.AlterField(
            model_name='groupmessage',
            name='to_group',
            field=models.CharField(choices=[('lecturers', 'Lecturers'), ('staffs', 'Staffs'), ('student', 'Students'), ('admins', 'Administrators'), ('all', 'All')], default='student', help_text='The category of people who will be recieving this message', max_length=60, null=True, verbose_name='To'),
        ),
        migrations.AlterField(
            model_name='message',
            name='to_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='to_user', to=settings.AUTH_USER_MODEL, verbose_name='To'),
        ),
        migrations.CreateModel(
            name='GrpMsg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.groupmessage')),
            ],
        ),
    ]
