# Generated by Django 3.2.5 on 2021-07-23 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_auto_20210723_1508'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupmessage',
            name='title',
        ),
        migrations.AddField(
            model_name='grpmsg',
            name='title',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
