# Generated by Django 3.2.5 on 2021-07-23 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('programme', '0009_alter_programme_id'),
        ('department', '0003_alter_department_id'),
        ('course', '0010_auto_20210717_0943'),
        ('chat', '0007_auto_20210723_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupmessage',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='department.department'),
        ),
        migrations.AlterField(
            model_name='groupmessage',
            name='level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='course.courselevel'),
        ),
        migrations.AlterField(
            model_name='groupmessage',
            name='programme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='programme.programme'),
        ),
    ]
