# Generated by Django 3.2.5 on 2021-07-23 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_auto_20210723_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupmessage',
            name='group_name',
            field=models.CharField(default=None, help_text='Name of this group', max_length=60, unique=True),
            preserve_default=False,
        ),
    ]
