# Generated by Django 3.2.5 on 2021-09-13 02:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0013_alter_coursemessage_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursemessage',
            name='sender',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, to='accounts.user'),
            preserve_default=False,
        ),
    ]
