# Generated by Django 3.0 on 2021-05-15 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20210509_1753'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ('last_name', 'first_name', 'username'), 'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
    ]
