# Generated by Django 3.2.5 on 2021-09-10 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_user_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_hod',
            field=models.BooleanField(default=False),
        ),
    ]
