# Generated by Django 3.2.5 on 2021-09-12 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_user_session_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='session_key',
            field=models.CharField(blank=True, max_length=32, null=True, unique=True),
        ),
    ]
