# Generated by Django 3.0 on 2021-05-09 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_remove_student_timestamp'),
        ('programme', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='programme',
            name='student',
            field=models.ManyToManyField(to='student.Student'),
        ),
    ]
