# Generated by Django 3.0 on 2021-05-09 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lecture', '0001_initial'),
        ('programme', '0002_programme_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='programme',
            name='lectures',
            field=models.ManyToManyField(to='lecture.LectureModel'),
        ),
    ]
