# Generated by Django 3.0 on 2021-05-15 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programme', '0005_auto_20210510_1544'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programme',
            name='course',
        ),
        migrations.RemoveField(
            model_name='programme',
            name='lectures',
        ),
        migrations.RemoveField(
            model_name='programme',
            name='student',
        ),
    ]
