# Generated by Django 3.0 on 2021-05-15 09:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0002_remove_department_programme'),
        ('programme', '0006_auto_20210515_0931'),
    ]

    operations = [
        migrations.AddField(
            model_name='programme',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='department.Department'),
        ),
    ]
