# Generated by Django 3.0 on 2021-06-02 20:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('setting', '0002_auto_20210602_2029'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminsetting',
            name='academic_year',
            field=models.CharField(default=2020, max_length=4),
        ),
        migrations.AddField(
            model_name='adminsetting',
            name='academic_year1',
            field=models.CharField(default=2021, max_length=4),
        ),
        migrations.AddField(
            model_name='adminsetting',
            name='created_by',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
