# Generated by Django 3.0 on 2021-06-02 21:23

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('setting', '0003_auto_20210602_2036'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AdminSetting',
            new_name='GeneralSetting',
        ),
    ]
