# Generated by Django 3.0 on 2021-06-02 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0004_auto_20210602_2123'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generalsetting',
            name='created_by',
        ),
    ]
