# Generated by Django 3.0 on 2021-06-03 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0007_auto_20210602_2157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalsetting',
            name='academic_year',
            field=models.CharField(default=2020, help_text='Academic year second part. 2020/2021. 2021 is second part', max_length=4),
        ),
        migrations.AlterField(
            model_name='generalsetting',
            name='academic_year1',
            field=models.CharField(default=2021, help_text='Academic year first part. 2020/2021. 2021 is first part', max_length=4),
        ),
        migrations.AlterField(
            model_name='generalsetting',
            name='name_order',
            field=models.CharField(choices=[('f', 'First Name'), ('l', 'Last Name')], default='f', help_text='How to order your name', max_length=20),
        ),
        migrations.AlterField(
            model_name='generalsetting',
            name='semester',
            field=models.CharField(choices=[('s1', 'First Semester'), ('s2', 'Second Semester')], default='s1', help_text='The current academic semester', max_length=60),
        ),
    ]
