# Generated by Django 3.0 on 2021-05-09 19:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_auto_20210509_1753'),
        ('student', '0002_remove_student_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.CourseLevel'),

        ),
    ]
