# Generated by Django 3.0 on 2021-05-17 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_student_programme'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ('level', 'programme', 'index_number')},
        ),
    ]
