# Generated by Django 3.0 on 2021-05-28 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_auto_20210517_1132'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ('programme', 'level', 'index_number')},
        ),
    ]
