# Generated by Django 3.2.5 on 2021-07-17 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_auto_20210528_1500'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ('programme', 'level', 'profile__first_name', 'profile__last_name', 'index_number')},
        ),
        migrations.AlterField(
            model_name='student',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
