# Generated by Django 3.0 on 2021-05-28 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('student', '0005_auto_20210517_1132'),
        ('assessment', '0021_auto_20210528_1014'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentResults',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
                ('question_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assessment.QuestionGroup')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.Student')),
            ],
        ),
    ]
