# Generated by Django 3.0 on 2021-06-08 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StudentResults',
        ),
    ]
