# Generated by Django 3.0 on 2021-05-15 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='programme',
        ),
    ]
